services:
  aeros-template:
    build:
      context: ./
    image: 'vite-portfolio'
    container_name: 'vite-portfolio'
    restart: unless-stopped
    command: bash -c "node index.js"
    ports:
      - '3000:3000'
